export interface Complaint {
  _id?: string; // optional, assigned by Sanity
  _type: "Complaints"; // document type
  complaint: string;
  complaint_status: string;
  complaint_date: string; // ISO date string
  complaint_category: string;
  complaint_place: string;
  complaint_description: string;
  complaint_name: string;
  complaint_person_nbr: string;
}

export interface Info {
  _id?: string; // optional, generated by Sanity
  _type: "Info"; // document type name
  title: string;
  description: string;
  image?: {
    _type: "image";
    asset: { _ref: string; _type: "reference" };
    alt?: string;
  };

  document?: {
    _type: "file";
    asset: {
      _ref: string;
      _type: "reference";
    };
  };
  info_date: string; // ISO date format
  info_category: string;
  info_status: string;
}

export interface Suggestion {
  _id?: string; // Optional, automatically generated by Sanity
  _type: "Suggestion"; // Document type name
  suggestion: string;
  suggestion_date: string; // ISO date string
  suggestion_category: string;
  suggestion_description: string;
  suggestion_person_name: string;
  suggestion_person_nbr: string;
  suggestion_person_email: string;
}
